# Generated by Django 4.0.5 on 2022-08-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='name',
            new_name='writer_name',
        ),
        migrations.AddField(
            model_name='blogs',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
