# Generated by Django 4.0.5 on 2022-08-06 15:18

from django.db import migrations, models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_blogs_writer_name_blogs_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='pic2',
            field=models.ImageField(blank=True, null=True, storage=main.storage.OverwriteStorage(), upload_to='courses'),
        ),
    ]
