# Generated by Django 4.0.5 on 2022-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
