# Generated by Django 4.0.5 on 2022-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_videos_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('keydata', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('contactNo', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
