# Generated by Django 4.0.6 on 2022-08-13 08:48

from django.db import migrations, models
import django.db.models.deletion
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blogs_description_para10_blogs_description_para11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='pic',
            field=models.ImageField(blank=True, null=True, storage=main.storage.OverwriteStorage(), upload_to='courses'),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('keydata', models.CharField(db_index=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('urlitem', models.CharField(blank=True, max_length=200, null=True)),
                ('lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lang', verbose_name='language21')),
            ],
        ),
    ]
